[package]
name = "open-library-client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
async-trait = "0.1.92"
bon = "3.10.0"
bytes = { version = "1.12.1", features = ["serde"] }
cached = { version = "4.0.0", features = ["async"] }
chrono = { version = "0.4.45", features = ["serde"] }
clap = { version = "4.6.6", features = ["cargo", "derive"] }
concat-idents = "1.1.5"
convert_case = "0.12.0"
getset = "0.1.7"
hex = { version = "0.4.3", features = ["serde"] }
open-library-client-macros = { workspace = true, optional = true }
parking_lot = { version = "0.12.5", features = ["arc_lock", "send_guard", "serde"] }
reqwest = { version = "0.13.4", features = ["cookies", "gzip", "json", "query", "rustls", "stream"] }
scraper = { version = "0.27.0", features = ["atomic", "deterministic", "serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_urlencoded = "0.7.1"
sha2 = "0.11.0"
thiserror = "2.0.20"
thiserror-ext = "0.3.0"
tokio = { version = "1.53.1", features = ["full"] }
url = { version = "2.5.8", features = ["serde"] }

[dev-dependencies]
dotenv = "0.15.0"

[features]
default = ["macros"]
macros = ["dep:open-library-client-macros"]
